# Generated by Django 5.2.17 on 2026-08-09 16:06

import accounts.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid Tanzanian phone number, e.g. +255712345678 or 0712345678.', regex='^\\+?255\\d{9}$|^0\\d{9}$')])),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('journalist', 'Journalist'), ('media_house', 'Media House'), ('moderator', 'Moderator'), ('admin', 'Admin'), ('super_admin', 'Super Admin')], db_index=True, default='buyer', max_length=20)),
                ('id_verification_status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='unsubmitted', max_length=20)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('is_2fa_enabled', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, editable=False, max_length=64)),
                ('is_suspended', models.BooleanField(default=False)),
                ('suspended_until', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('trust_score', models.PositiveSmallIntegerField(default=50, help_text='0-100 internal trust score, adjusted by moderation events.')),
                ('organization_name', models.CharField(blank=True, help_text='Media house / organization name, if applicable.', max_length=255)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='IdentityVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id_type', models.CharField(choices=[('nida', 'NIDA National ID'), ('passport', 'Passport'), ('drivers_license', "Driver's License"), ('voter_id', 'Voter ID')], default='nida', max_length=20)),
                ('front_image', models.ImageField(upload_to=accounts.models.national_id_upload_path)),
                ('back_image', models.ImageField(blank=True, null=True, upload_to=accounts.models.national_id_upload_path)),
                ('selfie_image', models.ImageField(upload_to=accounts.models.national_id_upload_path)),
                ('ocr_full_name', models.CharField(blank=True, max_length=255)),
                ('ocr_id_number', models.CharField(blank=True, max_length=64)),
                ('ocr_date_of_birth', models.DateField(blank=True, null=True)),
                ('ocr_raw_payload', models.JSONField(blank=True, default=dict)),
                ('ocr_confidence', models.FloatField(blank=True, null=True)),
                ('face_match_score', models.FloatField(blank=True, null=True)),
                ('liveness_passed', models.BooleanField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ocr_processing', 'OCR processing'), ('awaiting_review', 'Awaiting human review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoginSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TwoFactorRecoveryCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code_hash', models.CharField(max_length=128)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'id_verification_status'], name='accounts_us_role_0dd87e_idx'),
        ),
        migrations.AddIndex(
            model_name='identityverification',
            index=models.Index(fields=['user', 'status'], name='accounts_id_user_id_f7fc6e_idx'),
        ),
        migrations.AddIndex(
            model_name='twofactorrecoverycode',
            index=models.Index(fields=['user', 'used_at'], name='accounts_tw_user_id_aaf697_idx'),
        ),
    ]
