# Generated by Django 5.2.17 on 2026-08-14 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_deleted_at_user_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(blank=True, help_text='Short public profile bio, shown on listing pages.', max_length=500),
        ),
    ]
