# Generated by Django 5.2.17 on 2026-08-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_avatar_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified_badge',
            field=models.BooleanField(default=False, help_text="Editorial trust signal (Twitter/X blue-check style), distinct from id_verification_status -- that's 'we checked your ID', this is 'this is a notable/trusted publisher'. Moderator/admin-set only, never seller-settable."),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website_url',
            field=models.URLField(blank=True),
        ),
    ]
