# Generated by Django 5.2.17 on 2026-09-13 15:23

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_facebook_url_user_is_verified_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identityverification',
            name='press_credential_image',
            field=models.ImageField(blank=True, help_text="Optional: press card or media house accreditation letter, for journalist_tier='professional' claims. Reviewed alongside the rest of this submission; approving it sets User.is_press_credentialed rather than id_verification_status.", null=True, upload_to=accounts.models.national_id_upload_path),
        ),
        migrations.AddField(
            model_name='user',
            name='is_corporate',
            field=models.BooleanField(default=False, help_text='True once a CorporateVerification (business license / company registration / tax document) has been approved -- lets a buyer account represent an organization rather than an individual.'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_press_credentialed',
            field=models.BooleanField(default=False, help_text="Moderator-verified press credential (press card / media house letter), reviewed via the press_credential_image on the user's IdentityVerification submission. Distinct from is_verified_badge, which is a broader editorial trust signal."),
        ),
        migrations.AddField(
            model_name='user',
            name='journalist_tier',
            field=models.CharField(blank=True, choices=[('none', 'Not applicable'), ('citizen', 'Citizen Journalist'), ('professional', 'Professional Journalist')], default='none', help_text='Self-declared at registration for journalist/media_house accounts; the is_press_credentialed flag below is the moderator-verified confirmation of it.', max_length=20),
        ),
        migrations.CreateModel(
            name='CorporateVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=255)),
                ('business_license', models.FileField(upload_to=accounts.models.corporate_doc_upload_path)),
                ('company_registration', models.FileField(upload_to=accounts.models.corporate_doc_upload_path)),
                ('tax_document', models.FileField(blank=True, null=True, upload_to=accounts.models.corporate_doc_upload_path)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_corporate_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corporate_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='accounts_co_user_id_0560ce_idx')],
            },
        ),
    ]
