# Generated by Django 5.2.17 on 2026-09-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_identityverification_press_credential_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscription_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Monthly price for a buyer to subscribe to all of this seller's stories. Null/blank means this seller doesn't offer subscriptions.", max_digits=12, null=True),
        ),
    ]
