import phonenumbers
from phonenumbers import carrier, geocoder

num = phonenumbers.parse("+255712345678")

print("Valid:", phonenumbers.is_valid_number(num))
print("Country:", geocoder.description_for_number(num, "en"))
print("user_data:", num.user_data)
print("Carrier:", carrier.safe_display_name(num, "en"))
print("Carrier:", carrier.name_for_number(num, "en"))
print("Region Code:", phonenumbers.region_code_for_number(num))
print("Number Type:", phonenumbers.number_type(num))
print("National Format:", phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.NATIONAL))
print("International Format:", phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.INTERNATIONAL))
print("E164 Format:", phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.E164))
print("RFC3966 Format:", phonenumbers.format_number(num, phonenumbers.PhoneNumberFormat.RFC3966))
print("Original Number:", num.raw_input)
print("Country Code:", num.country_code)
print("National Number:", num.national_number)
print("Extension:", num.extension)
print("Leading Zero:", num.italian_leading_zero)
print("Number of Leading Zeros:", num.number_of_leading_zeros)
print("Preferred Domestic Carrier Code:", num.preferred_domestic_carrier_code)
print("Raw Input:", num.raw_input)
print("Country Code Source:", num.country_code_source)
print("Has Country Code:", num.HasField("country_code"))
print("Has National Number:", num.HasField("national_number"))
print("Has Extension:", num.HasField("extension"))
print("Has Italian Leading Zero:", num.HasField("italian_leading_zero"))
print("Has Number of Leading Zeros:", num.HasField("number_of_leading_zeros"))
print("Has Preferred Domestic Carrier Code:", num.HasField("preferred_domestic_carrier_code"))
