# Generated by Django 5.2.17 on 2026-08-09 16:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reason', models.CharField(choices=[('misinformation', 'Misinformation'), ('fraud', 'Fraud / scam'), ('off_platform_solicitation', 'Off-platform solicitation'), ('harassment', 'Harassment'), ('copyright', 'Copyright infringement'), ('other', 'Other')], max_length=30)),
                ('details', models.TextField(blank=True)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='news.newslisting')),
                ('reported_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports_against', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserViolationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warning_count', models.PositiveIntegerField(default=0)),
                ('suspension_count', models.PositiveIntegerField(default=0)),
                ('last_violation_at', models.DateTimeField(blank=True, null=True)),
                ('is_banned', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='violation_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AntiCircumventionFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_type', models.CharField(choices=[('listing_description', 'News listing description'), ('listing_body', 'News listing body'), ('message', 'Direct/marketplace message'), ('comment', 'Comment')], max_length=30)),
                ('detected_pattern', models.CharField(choices=[('phone_number', 'Phone number'), ('email', 'Email address'), ('whatsapp', 'WhatsApp number/handle'), ('telegram', 'Telegram handle'), ('social_handle', 'Social media handle'), ('off_platform_language', 'Off-platform payment language')], db_index=True, max_length=30)),
                ('matched_text', models.CharField(blank=True, help_text='Redacted/masked snippet of the matched content, not full raw text.', max_length=255)),
                ('confidence', models.FloatField(default=0)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='low', max_length=10)),
                ('action_taken', models.CharField(choices=[('none', 'No action'), ('warning', 'Warning issued'), ('content_blocked', 'Content blocked'), ('temporary_suspension', 'Temporary suspension'), ('permanent_ban', 'Permanent ban')], default='none', max_length=20)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circumvention_flags', to='news.newslisting')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='circumvention_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='circumvention_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'severity'], name='moderation__user_id_caf6a0_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModerationQueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_type', models.CharField(choices=[('news_verification', 'News AI verification'), ('identity_verification', 'Identity verification'), ('circumvention_flag', 'Anti-circumvention flag'), ('user_report', 'User-submitted report')], db_index=True, max_length=30)),
                ('related_object_id', models.UUIDField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=15)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_moderation_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['item_type', 'status'], name='moderation__item_ty_dc2b0b_idx')],
            },
        ),
    ]
