# Generated by Django 5.2.17 on 2026-08-09 16:06

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_platform', models.BooleanField(db_index=True, default=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Funds credited but held (e.g. pending withdrawal review).', max_digits=14)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('is_frozen', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entry_type', models.CharField(choices=[('sale_credit', 'Sale credit (seller earning)'), ('commission_credit', 'Commission credit (platform)'), ('withdrawal_debit', 'Withdrawal debit'), ('refund_debit', 'Refund debit'), ('refund_reversal_credit', 'Refund reversal credit'), ('adjustment', 'Manual adjustment')], db_index=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive = credit, negative = debit.', max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_entries', to='payments.order')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('destination_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_account', 'Bank Account')], max_length=20)),
                ('destination_details', models.JSONField(default=dict, help_text="e.g. {'msisdn': '+255712345678'} or bank account details.")),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('failed', 'Failed')], db_index=True, default='requested', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('payout_reference', models.CharField(blank=True, max_length=100)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_reviews', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='wallet.wallet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(condition=models.Q(('is_platform', True)), fields=('is_platform',), name='unique_platform_wallet'),
        ),
        migrations.AddIndex(
            model_name='wallettransaction',
            index=models.Index(fields=['wallet', 'entry_type'], name='wallet_wall_wallet__ea6f79_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['wallet', 'status'], name='wallet_with_wallet__b8c63b_idx'),
        ),
    ]
