# Generated by Django 5.2.17 on 2026-08-13 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawalrequest',
            name='destination_details',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy freeform destination info. New requests should use payout_account instead.'),
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_type', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('bank_account', 'Bank Account')], max_length=20)),
                ('provider', models.CharField(blank=True, help_text='e.g. M-Pesa, Airtel Money, Tigo Pesa, CRDB Bank, NMB Bank.', max_length=100)),
                ('account_number', models.CharField(help_text='Phone number or bank account number.', max_length=100)),
                ('account_name', models.CharField(help_text='Name the account is registered under.', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payout_account_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='payout_account',
            field=models.ForeignKey(blank=True, help_text='Preferred over destination_details for new requests; kept nullable for backward compatibility with withdrawal requests created before this model existed.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='withdrawal_requests', to='wallet.payoutaccount'),
        ),
        migrations.AddIndex(
            model_name='payoutaccount',
            index=models.Index(fields=['user', 'status'], name='wallet_payo_user_id_c5b2de_idx'),
        ),
    ]
