# Generated by Django 5.2.17 on 2026-09-13 20:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_withdrawalrequest_risk_flagged_companypayoutaccount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('matures_at', models.DateTimeField(db_index=True)),
                ('released', models.BooleanField(db_index=True, default=False)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='wallet.wallettransaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='wallet.wallet')),
            ],
            options={
                'ordering': ['matures_at'],
                'indexes': [models.Index(fields=['wallet', 'released'], name='wallet_wall_wallet__4c4b5a_idx')],
            },
        ),
    ]
