# Generated by Django 5.2.17 on 2026-08-15 09:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_provider',
            field=models.CharField(choices=[('selcom', 'Selcom (Tanzania mobile money/cards)'), ('nala', 'Nala/Rafiki (international)')], default='selcom', help_text='Which payment rail this order was checked out through. Selcom for local TZS payments; Nala/Rafiki for international buyers.', max_length=20),
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='provider',
            field=models.CharField(choices=[('selcom', 'Selcom (Tanzania mobile money/cards)'), ('nala', 'Nala/Rafiki (international)')], default='selcom', max_length=20),
        ),
        migrations.CreateModel(
            name='NalaTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nala_collection_id', models.CharField(help_text="Nala's ID for this collection request, once real API integration exists.", max_length=100, unique=True)),
                ('reference', models.CharField(help_text='Our internal idempotency reference.', max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('card', 'Card'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('stablecoin', 'Stablecoin (USDC/USDT)')], default='card', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='initiated', max_length=20)),
                ('nala_transaction_id', models.CharField(blank=True, max_length=100)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nala_transactions', to='payments.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentwebhooklog',
            name='nala_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='payments.nalatransaction'),
        ),
        migrations.AddIndex(
            model_name='nalatransaction',
            index=models.Index(fields=['order', 'status'], name='payments_na_order_i_0f53e1_idx'),
        ),
    ]
