# Generated by Django 5.2.17 on 2026-09-15 15:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_order_payment_provider_paymentwebhooklog_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Active'), ('cancelled', 'Cancelled (access continues until period end)'), ('expired', 'Expired')], db_index=True, default='pending_payment', max_length=20)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers_list', to=settings.AUTH_USER_MODEL)),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('selcom_order_id', models.CharField(max_length=100, unique=True)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('channel', models.CharField(choices=[('mobile_money', 'Mobile Money'), ('card', 'Card'), ('bank', 'Bank')], max_length=20)),
                ('msisdn', models.CharField(blank=True, max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='initiated', max_length=20)),
                ('selcom_transaction_id', models.CharField(blank=True, max_length=100)),
                ('selcom_resultcode', models.CharField(blank=True, max_length=20)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='payments.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending_payment', 'active'])), fields=('subscriber', 'seller'), name='unique_active_subscription_per_pair'),
        ),
        migrations.AddIndex(
            model_name='subscriptiontransaction',
            index=models.Index(fields=['subscription', 'status'], name='payments_su_subscri_b62d82_idx'),
        ),
    ]
