# Generated by Django 5.2.17 on 2026-08-09 16:06

import django.db.models.deletion
import news.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=60, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsListing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=280, unique=True)),
                ('description', models.TextField()),
                ('body', models.TextField(help_text='Full article body, only released to buyers after purchase.')),
                ('news_type', models.CharField(choices=[('text', 'Text News'), ('image', 'Image News'), ('video', 'Video News'), ('breaking', 'Breaking News'), ('investigative', 'Investigative Report'), ('political', 'Political News'), ('business', 'Business News'), ('sports', 'Sports News')], db_index=True, max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='TZS', max_length=3)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('partially_verified', 'Partially verified'), ('needs_human_review', 'Needs human review'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=25)),
                ('ai_score', models.FloatField(blank=True, help_text='Overall AI confidence score (0-100) from the verification engine.', null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('published', 'Published'), ('suspended', 'Suspended'), ('removed', 'Removed'), ('sold_out', 'Sold out')], db_index=True, default='draft', max_length=20)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('purchase_count', models.PositiveIntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='news.category')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_listings', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='listings', to='news.tag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document')], max_length=10)),
                ('file', models.FileField(upload_to=news.models.news_media_upload_path)),
                ('preview_file', models.FileField(blank=True, null=True, upload_to=news.models.news_media_upload_path)),
                ('is_cover', models.BooleanField(default=False)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='news.newslisting')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageAnalysisResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manipulation_score', models.FloatField(default=0, help_text='0-100, higher = more likely manipulated.')),
                ('deepfake_score', models.FloatField(default=0)),
                ('metadata_valid', models.BooleanField(blank=True, null=True)),
                ('exif_payload', models.JSONField(blank=True, default=dict)),
                ('reverse_image_matches', models.JSONField(blank=True, default=list, help_text='List of {url, similarity, source} matches found.')),
                ('authenticity_score', models.FloatField(default=0)),
                ('flagged', models.BooleanField(default=False)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_results', to='news.newsmedia')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIVerificationResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fake_news_score', models.FloatField(help_text='0-100, higher = more likely fake.')),
                ('misinformation_score', models.FloatField(default=0)),
                ('clickbait_score', models.FloatField(default=0)),
                ('authenticity_score', models.FloatField(default=0)),
                ('sentiment_score', models.FloatField(default=0, help_text='-1 (very negative) to +1 (very positive).')),
                ('similarity_score', models.FloatField(default=0, help_text='Highest similarity to existing content, 0-100.')),
                ('risk_score', models.FloatField(default=0)),
                ('confidence_score', models.FloatField(help_text='Overall model confidence, 0-100.')),
                ('outcome', models.CharField(choices=[('verified', 'Verified'), ('partially_verified', 'Partially verified'), ('needs_human_review', 'Needs human review'), ('rejected', 'Rejected')], db_index=True, max_length=25)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('reviewed_by_human', models.BooleanField(default=False)),
                ('human_notes', models.TextField(blank=True)),
                ('human_reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_reviews', to=settings.AUTH_USER_MODEL)),
                ('duplicate_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicates_of_this', to='news.newslisting')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_verifications', to='news.newslisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'outcome'], name='news_aiveri_listing_300346_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='newslisting',
            index=models.Index(fields=['status', 'verification_status'], name='news_newsli_status_029b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='newslisting',
            index=models.Index(fields=['news_type', 'category'], name='news_newsli_news_ty_c2b033_idx'),
        ),
    ]
