# Generated by Django 5.2.17 on 2026-08-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newslisting_average_rating_newslisting_review_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslisting',
            name='meta_description',
            field=models.CharField(blank=True, help_text='SEO meta description. Auto-derived from `description` if left blank.', max_length=300),
        ),
    ]
