# Generated by Django 5.2.17 on 2026-08-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslisting',
            name='byline',
            field=models.CharField(blank=True, help_text="Credited author, if different from the seller account. E.g. wire-service convention where the account holder and the reporting journalist aren't always the same person.", max_length=255),
        ),
        migrations.AddField(
            model_name='newslisting',
            name='dateline',
            field=models.CharField(blank=True, help_text="Standard news dateline: where (and optionally when) the story was reported, e.g. 'DAR ES SALAAM, Aug 14'.", max_length=255),
        ),
        migrations.AddField(
            model_name='newslisting',
            name='featured',
            field=models.BooleanField(db_index=True, default=False, help_text='Manually curated by a moderator/admin for homepage highlighting -- not seller-settable.'),
        ),
        migrations.AddField(
            model_name='newslisting',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=1, help_text='Auto-computed from body word count (~200 wpm) on save.'),
        ),
    ]
