# Generated by Django 5.2.17 on 2026-09-13 16:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_newslistingrevision'),
        ('payments', '0002_order_payment_provider_paymentwebhooklog_provider_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialShareRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to='news.newslisting')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_shares', to='payments.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_shares', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['listing', 'provider'], name='news_social_listing_7588f6_idx')],
            },
        ),
    ]
