# Generated by Django 5.2.17 on 2026-09-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_correction'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmedia',
            name='capture_date',
            field=models.DateTimeField(blank=True, help_text='When the photo/video was actually captured, distinct from when it was uploaded/published.', null=True),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='credit_line',
            field=models.CharField(blank=True, help_text="Attribution text required when this media is republished, e.g. 'Photo: Jane Reporter / WEMIX'.", max_length=255),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='newsmedia',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated search keywords, wire-service style.', max_length=500),
        ),
    ]
