# Generated by Django 5.2.17 on 2026-09-15 15:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_newsmedia_capture_date_newsmedia_credit_line_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, help_text="A label for the buyer's own reference, e.g. 'Dar es Salaam politics'.", max_length=100)),
                ('news_type', models.CharField(blank=True, choices=[('text', 'Text News'), ('image', 'Image News'), ('video', 'Video News'), ('breaking', 'Breaking News'), ('investigative', 'Investigative Report'), ('political', 'Political News'), ('business', 'Business News'), ('sports', 'Sports News')], max_length=20)),
                ('location_contains', models.CharField(blank=True, max_length=255)),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='news.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='news_saveds_is_acti_74c96b_idx')],
            },
        ),
    ]
