# Generated by Django 5.2.17 on 2026-09-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_savedsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslisting',
            name='license_territory',
            field=models.CharField(blank=True, default='Worldwide', help_text="Where the buyer's usage rights apply, e.g. 'Worldwide', 'Tanzania only', 'East Africa'.", max_length=100),
        ),
        migrations.AddField(
            model_name='newslisting',
            name='license_type',
            field=models.CharField(choices=[('standard', 'Standard (non-exclusive, digital use)'), ('exclusive', 'Exclusive (only one buyer -- listing is withdrawn from sale after purchase)'), ('broadcast', 'Includes broadcast rights (non-exclusive)')], default='standard', max_length=20),
        ),
    ]
