# Generated by Django 5.2.17 on 2026-09-15 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_newslisting_license_territory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FreePreviewGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month_key', models.CharField(db_index=True, help_text="'YYYY-MM' of when this preview was granted.", max_length=7)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_preview_grants', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_preview_grants', to='news.newslisting')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('buyer', 'listing', 'month_key'), name='unique_free_preview_per_buyer_listing_month')],
            },
        ),
    ]
