# Generated by Django 5.2.17 on 2026-09-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_freepreviewgrant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialsharerecord',
            name='provider',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('x', 'X (Twitter)'), ('linkedin', 'LinkedIn'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('email', 'Email'), ('copy_link', 'Copy link'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('youtube', 'YouTube')], max_length=20),
        ),
    ]
