# Generated by Django 5.2.17 on 2026-08-13 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing rejected'), ('listing_needs_review', 'Listing needs human review'), ('kyc_approved', 'Identity verification approved'), ('kyc_rejected', 'Identity verification rejected'), ('sale_completed', 'Sale completed'), ('withdrawal_completed', 'Withdrawal completed'), ('withdrawal_rejected', 'Withdrawal rejected'), ('refund_processed', 'Refund processed'), ('moderation_action', 'Moderation action taken'), ('new_review', 'New review received')], db_index=True, max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('link_path', models.CharField(blank=True, help_text="Relative frontend path to link to, e.g. 'dashboard.html?tab=listings'.", max_length=255)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read', '-created_at'], name='core_notifi_user_id_f286cd_idx')],
            },
        ),
    ]
