# Generated by Django 5.2.17 on 2026-08-16 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('selcom', 'Selcom'), ('nala', 'Nala/Rafiki'), ('ai_verification', 'AI Verification'), ('email', 'Email (SMTP)')], db_index=True, max_length=30)),
                ('field_name', models.CharField(help_text='e.g. api_key, api_secret, vendor_id, base_url, host, port.', max_length=100)),
                ('encrypted_value', models.TextField(blank=True, help_text="Fernet-encrypted. Empty means 'not set / cleared'.")),
                ('is_secret', models.BooleanField(default=True, help_text="Secret fields (API keys, passwords) are masked in every API response. Non-secret fields (a base URL, a port number) are returned in full since there's nothing to protect.")),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['provider', 'field_name'],
                'constraints': [models.UniqueConstraint(fields=('provider', 'field_name'), name='unique_credential_field_per_provider')],
            },
        ),
    ]
