# Generated by Django 5.2.17 on 2026-09-15 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notification_notification_type_supportticket_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('listing_approved', 'Listing approved'), ('listing_rejected', 'Listing rejected'), ('listing_needs_review', 'Listing needs human review'), ('kyc_approved', 'Identity verification approved'), ('kyc_rejected', 'Identity verification rejected'), ('sale_completed', 'Sale completed'), ('withdrawal_completed', 'Withdrawal completed'), ('withdrawal_rejected', 'Withdrawal rejected'), ('refund_processed', 'Refund processed'), ('moderation_action', 'Moderation action taken'), ('new_review', 'New review received'), ('support_ticket_reply', 'Support ticket reply'), ('saved_search_match', 'New listing matches a saved search'), ('subscription_renewal_due', 'Subscription renewal due'), ('subscription_activated', 'Subscription activated')], db_index=True, max_length=30),
        ),
    ]
